version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=53b81d229a621a49909f3eb9170dd074c2c561909ba301ff68fae030f989c031a663262eed1e0a6afbe86a9aef09a4465f67a681495e697e0bb466e5934ecd8e
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - app_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app_data: